import chess

tn = []
for rank in reversed(range(1,9)):
    for file in 'ABCDEFGH':
        tn.append(file+str(rank))
def lookup(x):
    match x:
        case 1:
            return chess.A8    
        case 2:
            return chess.B8
        case 3:
            return chess.C8
        case 4:
            return chess.D8
        case 5:
            return chess.E8
        case 6:
            return chess.F8
        case 7:
            return chess.G8
        case 8:
            return chess.H8
        case 9:
            return chess.A7
        case 10:
            return chess.B7
        case 11:
            return chess.C7
        case 12:
            return chess.D7
        case 13:
            return chess.E7
        case 14:
            return chess.F7
        case 15:
            return chess.G7
        case 16:
            return chess.H7
        case 17:
            return chess.A6
        case 18:
            return chess.B6
        case 19:
            return chess.C6
        case 20:
            return chess.D6
        case 21:
            return chess.E6
        case 22:
            return chess.F6
        case 23:
            return chess.G6
        case 24:
            return chess.H6
        case 25:
            return chess.A5
        case 26:
            return chess.B5
        case 27:
            return chess.C5
        case 28:
            return chess.D5
        case 29:
            return chess.E5
        case 30:
            return chess.F5
        case 31:
            return chess.G5
        case 32:
            return chess.H5
        case 33:
            return chess.A4
        case 34:
            return chess.B4
        case 35:
            return chess.C4
        case 36:
            return chess.D4
        case 37:
            return chess.E4
        case 38:
            return chess.F4
        case 39:
            return chess.G4
        case 40:
            return chess.H4
        case 41:
            return chess.A3
        case 42:
            return chess.B3
        case 43:
            return chess.C3
        case 44:
            return chess.D3
        case 45:
            return chess.E3
        case 46:
            return chess.F3
        case 47:
            return chess.G3
        case 48:
            return chess.H3
        case 49:
            return chess.A2
        case 50:
            return chess.B2
        case 51:
            return chess.C2
        case 52:
            return chess.D2
        case 53:
            return chess.E2
        case 54:
            return chess.F2
        case 55:
            return chess.G2
        case 56:
            return chess.H2
        case 57:
            return chess.A1
        case 58:
            return chess.B1
        case 59:
            return chess.C1
        case 60:
            return chess.D1
        case 61:
            return chess.E1
        case 62:
            return chess.F1
        case 63:
            return chess.G1
        case 64:
            return chess.H1

def writeCode():
    for x in range(1,65):
        print("case {}:".format(x))
        print("    return chess."+tn[x-1])

